### ISSUE TITLE
Don't cache specific API calls

### ISSUE THREAD

**Issue by simplenotezy** [DreaMinder/nuxt-payload-extractor#12]
Is it possible to not cache specific API calls? Say I have an e-commerce shop, I don't mind all the product page responses are cached, but I'd prefer if "add to cart" response is not cached, and also product variations API request.

**Comment by DreaMinder** [comment]
@simplenotezy generally it's possible, but I'm not sure about your case.
Two steps:
1. Exclude specific paths you want to be ignored by using `blacklist` option:
```
['nuxt-payload-extractor, {
      blacklist: ['/'],
    }
]
```
2. Remove this code from asyncData
```
if(process.static && process.client && $payloadURL)
    return await $axios.$get($payloadURL(route))
```
from the route you don't want to be cached

**Comment by simplenotezy** [comment]
Thanks for a prompt reply @DreaMinder! I'll play around with it

**Comment by DreaMinder** [comment]
I hope you figured it out
