### ISSUE TITLE
asyncData and vuex

### ISSUE THREAD

**Issue by simplenotezy** [DreaMinder/nuxt-payload-extractor#13]
In my asyncData I usually don't return data, instead I assign the data to the vuex store. How is this possible with this module?

**Comment by DreaMinder** [comment]
@simplenotezy actually your approach is not compatible with this module, this is what I meant by saying
> There may be issues with vuex data requests

in Readme. At least this was my conclusion while I was trying to do the same thing on the early development stages. But honestly, I don't remember why exactly it didn't work. Therefore, I may be wrong...

If it's OK for you to change your approach, you can rewrite data-requests to return all the data from asyncData method:
```
await store.dispatch('getData')
return store.state.data
```
If you have global data, you can put it in nuxtServerInit (it will trigger on every route), it should work.

**Comment by DreaMinder** [comment]
... this module meant to be a temporary solution until Nuxt comes up with a similar native feature. But looks like we are forced to wait for Vue 3 release anyways to have this feature in Nuxt. So I'll take a look again at your issue a little bit later in case there is actually a solution.

**Comment by simplenotezy** [comment]
That would be sweet -- looking forward to it!

**Comment by DreaMinder** [comment]
@simplenotezy I checked again and now I remember why vuex-data issue can't be solved easily. 
Let's say I'll add a fix in order to have vuex-data in payload.json on client-side navigation. But how would you shove it back to vuex on page init during client-side navigation?
The current approach only returns component-level data with the same keys. But vuex requires mutations to refill the store. And every namespaced vuex-module requires its own mutation.
It would look like this
```
async asyncData({ $axios, $payloadURL, store, route }){
  if(process.static && process.client && $payloadURL) {
    const {data, storeState} = await $axios.$get($payloadURL(route))
    store.commit('news/INIT_NEWS_MODULE', storeState.news)
    store.commit('articles/INIT_ARTICLES_MODULE', storeState.articles)
    return data
  } 
  //your request logic
  let post = await $axios.$get(`/post.json`)
  return {
    post
  }
}
```
I think it's better to avoid such complicated approach. And I don't see any alternatives.

**Comment by simplenotezy** [comment]
So in theory your posted code works?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by DreaMinder** [comment]
@simplenotezy it should work after
1. I'll add a fix to the module.
2. You'll add INIT_MODULE mutation to every module.
3. You'll modify your asyncData code as in the example I posted.

The fix involves breaking change that will force every user to modify their asyncData code (even without vuex on their projects), so I think it makes sense to implement it in a separate repo. Fork this project and I'll help you to implement it there.

**Comment by simplenotezy** [comment]
@DreaMinder that's cool. I forked it and invited you.

**Comment by DreaMinder** [comment]
added the implementation mentioned above here https://github.com/simplenotezy/nuxt-payload-extractor/pull/1
