### ISSUE TITLE
Route ending in forward slash causes double forward slash in payload path

### ISSUE THREAD

**Issue by ProTip** [DreaMinder/nuxt-payload-extractor#4]
Sometimes `route.path` has a trailing slash and this results in a payload URL like `https://www.example.com/foo//payload.json`. Some servers handle this, however AWS S3 views this as a separate, non-existent, object key.

Something like this may work better:
```js
return document.location.origin + route.path.replace(/\/+$/, "") + '/payload.json'
```

**Comment by DreaMinder** [comment]
@ProTip Thank you for ready solution! Published this patch on npm.
