### ISSUE TITLE
nuxt generate with custom 'dir' is not working

### ISSUE THREAD

**Issue by asif-ahmed-1990** [DreaMinder/nuxt-payload-extractor#8]
I am using `nuxt generate` with a custom directory - https://nuxtjs.org/api/configuration-generate/#dir.

I am generating the builds in `dist/apps`

The links for the payload thus points to the wrong directory.

Can this be fixed or is a workaround available? Ideally, the package should take this property into consideration or maybe work with relative URLs.

https://github.com/DreaMinder/nuxt-payload-extractor/blob/17571b6745c7c3d63989550212c8319fcf4c9323/lib/module.js#L11

Looking forward to your input @DreaMinder.

Thanks 😄

**Comment by DreaMinder** [comment]
@asifahmedfw I tested and It works as it should - it extracts data to dist/apps and the app can be started from apps dir. This dir-option is already handled on line 68.

In case you expected to open http://localhost/apps/page URL in browser, you may want to check this option instead https://nuxtjs.org/api/configuration-router#base. Let me know if that what you were looking for. 
This option is not supported by the module yet.

**Comment by asif-ahmed-1990** [comment]
Yes. I guess that is what I was looking for. 
The payload is generated correctly in the directory. However, the script tag in the html points with respect to the host URL. I have implemented a workaround to skip the path while generating the script tag. In that way, it is using the URL relative to the current directory which in turn accesses the correct payload.js.
I hope this makes sense.

**Comment by DreaMinder** [comment]
@asifahmedfw I've pushed new version 12 that should add support for router-base. Can you make some tests (with and without /apps prefix)?

**Comment by DreaMinder** [comment]
@asifahmedfw Hi. Any updates? Does it work for you?

**Comment by asif-ahmed-1990** [comment]
Hey, sorry for the late reply. Sorry, it doesn't work for me. The reason being I am using [router-module.](https://github.com/nuxt-community/router-module). Hence, I am not getting a router object at the following line.
https://github.com/DreaMinder/nuxt-payload-extractor/blob/16d2191b90be28f8d83d76b8e7f2f2c5912d6c15/lib/module.js#L65

My project is running with nuxt@2.3.4 and nuxtjs/router@1.1.0.

**Comment by DreaMinder** [comment]
@asifahmedfw Oh... I don't think I can help you in this case, sorry.
Nuxt 3 will have this static-payload feature in its core, maybe it will work for you when released.

**Comment by asif-ahmed-1990** [comment]
Thanks a lot for your help. 😄
